### ISSUE TITLE
Possible DecoID info and mishaps

### ISSUE THREAD

**Issue by Texthead** [NefariousTechSupport/Runes#1]
Not completely based around an issue with the code, but it's some info I've collected in regards to the DecoID in some figures, with a custom program based on the info here.

I've playtested some code to gather the DecoID, tested and should be all correct.

So, for a figure like Super Gulp Pop Fizz (the short for his variantID is 10245), the following info is gathered:

> DecoID: 5 (kTfbSpyroTag_DecoID_Repose2)
> IsSuperCharger: False
> IsLightCore: False
> IsAltDeco: False
> IsRepose: True
> YearCode: 2 (eSG_Shapeshifters2013)

...all seems correct. (Swap-Force uses Repose2 for all of its reposes - from what I've tested - as it's the 2nd game in the index. The same goes for Giants, using Repose1. Whereas Trap Team uses the series number - Hog Wild Fryno uses Repose1 even though it's the 4th game - for reference for the reposes)

Love Potion Pop Fizz (15362) gives out:

> DecoID: 2 (kTfbSpyroTag_DecoID_AlternateDeco)
> IsSuperCharger: False
> IsLightCore: False
> IsAltDeco: True
> IsRepose: True
> YearCode: 3 (eSG_TrapTeam2014)

So for Love Potion the fact that it is an AltDeco overrides the repose factor for the DecoID.

Event Exclusive Hot Streak (16388) gives out:

> DecoID: 4 (kTfbSpyroTag_DecoID_Event)
> IsSuperCharger: False
> IsLightCore: False
> IsAltDeco: False
> IsRepose: False
> YearCode: 4 (eSG_Superchargers2015)

So the DecoID tells us it is an event figure, and it's also not an alt deco with IsAltDeco being false, which is odd considering it **is** an alt deco in SuperChargers mainline, but does get considered a special in SSC Racing. They must've just allowed the in-game version to become an Alt Deco without technically being one?

Tested Candy-Coated Chopscotch, and I do get the DecoID 21 (kTfbSpyroTag_DecoID_Halloween) as expected, as well as the AltDeco part, but oddly...

...it seems that Colour Shift Hot Dog is also a Halloween, not a Colour Shift or Event like I assumed:
Colour Shift Hot Dog (4117) gives out:

> DecoID: 21 (kTfbSpyroTag_DecoID_Halloween)
> IsSuperCharger: False
> IsLightCore: False
> IsAltDeco: False
> IsRepose: False
> YearCode: 1 (eSG_Giants2012)

And the Purple Crystal Frito-Lay Hot Dog (10268) gives out:

> DecoID: 28 (this is one that doesn't exist in the [DecoID enum](https://github.com/NefariousTechSupport/Runes/blob/master/include/kTfbSpyroTag_DecoID.hpp))
> IsSuperCharger: False
> IsLightCore: False
> IsAltDeco: False
> IsRepose: True
> YearCode: 2 (eSG_Shapeshifters2013)

So its DecoID doesn't seem to match up with anything...?

Trap Team's re-releases of Sidekicks also aren't reposed, they're just Year 4 versions. This is why they **normally** don't show up as a special, but I did find in the SSC Collection menu they are considered Special, and 3DS Giants shows the text "Series 1" (tested Trigger Snappy) - normal Sidekicks show no additional text.

And just to end things:

Gold Flameslinger S2 (6164) gives out:

> DecoID: 2 (kTfbSpyroTag_DecoID_AlternativeDeco)
> IsSuperCharger: False
> IsLightCore: False
> IsAltDeco: False
> IsRepose: True
> YearCode: 1 (eSG_Giants2012)

So here, the DecoID hints at it being an AltDeco, but it clearly isn't, like the opposite to the Event Exclusive Hot Streak.

Some additional notes:
**Most** figures with lights are considered LightCore (from what I've tested), even if they don't show it in-game. This includes Giants and Battle Pack items. Creation Crystals have the IsLightCore tag, but the variant of the Crystal overrides the DecoID

Birthday Bash Big Bubble Pop Fizz is considered to be a Winter variant.

Heartbreaker Buckshot might be the only figure considered to be a Valentines variant, as Love Potion isn't.

They were playing a bit weird with this some bits and pieces, huh?

**Comment by NefariousTechSupport** [comment]
Indeed they were, the deco id doesn't really have to match with anything at all since none of these variables have specific meanings except maybe the year code, the rest are just identifiers and nothing more.
